# Generated by Django 2.1.5 on 2019-05-01 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aceleracao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataInicio', models.DateTimeField()),
                ('acrescimoSegundos', models.FloatField()),
                ('orientacao', models.CharField(max_length=1)),
                ('aceleracao', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Acelerometro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('descricao', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('descricao', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='aceleracao',
            name='acelerometro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aceleracao_acelerometro', to='bloco.Acelerometro'),
        ),
        migrations.AddField(
            model_name='aceleracao',
            name='bloco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aceleracao_bloco', to='bloco.Bloco'),
        ),
    ]
