# Generated by Django 2.1.5 on 2019-04-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('descricao', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=100)),
            ],
        ),
    ]
