# Generated by Django 2.1.5 on 2019-05-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloco', '0002_remove_bloco_localizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='aceleracao',
            name='leitura',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
