# Generated by Django 2.1.5 on 2019-05-01 22:54

from django.db import migrations, models
from datetime import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('bloco', '0003_aceleracao_leitura'),
    ]

    operations = [
        migrations.AddField(
            model_name='aceleracao',
            name='dataReal',
            field=models.DateTimeField(default=datetime.now()),
            preserve_default=False,
        ),
    ]
