# Generated by Django 2.2.4 on 2019-08-08 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acelerometro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('descricao', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('arquivo', models.FileField(upload_to='')),
                ('data', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FDD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Graficator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.IntegerField()),
                ('fourierSize', models.IntegerField()),
                ('graus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Aceleracao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataInicio', models.DateTimeField()),
                ('acrescimoSegundos', models.FloatField()),
                ('dataReal', models.DateTimeField()),
                ('orientacao', models.CharField(max_length=1)),
                ('aceleracao', models.FloatField()),
                ('leitura', models.BigIntegerField()),
                ('acelerometro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aceleracao_acelerometro', to='fdd.Acelerometro')),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aceleracao_bloco', to='fdd.Bloco')),
            ],
        ),
    ]
