# Generated by Django 2.2.4 on 2019-08-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdd', '0002_auto_20190808_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoFdd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30)),
                ('arquivo', models.FileField(upload_to='')),
                ('canais', models.SmallIntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('dataInicio', models.DateTimeField()),
                ('frequencia', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Arquivo',
        ),
        migrations.DeleteModel(
            name='FDD',
        ),
    ]
