# Generated by Django 2.2.4 on 2019-08-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdd', '0004_arquivofdd_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='FDD',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='arquivofdd',
            name='arquivo',
            field=models.FileField(upload_to='fdd_files'),
        ),
    ]
