# Generated by Django 2.1.5 on 2019-03-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acelerometro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='desvioPadrao',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='frequenciaTempo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='media',
            field=models.FloatField(),
        ),
    ]
