# Generated by Django 2.1.5 on 2019-03-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acelerometro', '0002_auto_20190330_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='leitura',
            name='registro',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
