# Generated by Django 2.1.5 on 2019-03-30 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acelerometro', '0004_auto_20190330_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
