# Generated by Django 2.1.5 on 2019-03-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='imageTop',
            field=models.ImageField(blank=True, null=True, upload_to='image_perfil'),
        ),
    ]
