# Generated by Django 2.1.5 on 2019-03-30 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190330_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='imageTop',
        ),
    ]
